apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: review-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: review.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: review-service
                port:
                  number: 80
    - host: auth.review.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: review-keycloak
                port:
                  number: 8080
    - host: review-rabbitmq.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: review-rabbitmq
                port:
                  number: 15672
