apiVersion: v1
kind: Secret
metadata:
  name: books-secret
type: Opaque
stringData:
  connection-string: "Host=postgres;Port=5432;Database=BooksDB;Username=books_user;Password=books_password;Timeout=30;Command Timeout=30"