apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookreview-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: bookreview.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: review-service
                port:
                  number: 80
    - host: auth.bookreview.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
    - host: rabbitmq.bookreview.local
      http:
        paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: rabbitmq
                  port:
                    number: 15672
