apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  connection-string: "Host=postgres;Port=5432;Database=ReviewDB;Username=review_user;Password=review_password;Timeout=30;Command Timeout=30"
