apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-postgres
  template:
    metadata:
      labels:
        app: book-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: book_user
            - name: POSTGRES_PASSWORD
              value: book_password
            - name: POSTGRES_DB
              value: BookDB
          volumeMounts:
            - name: book-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: book-postgres-data
          emptyDir: {}
