apiVersion: v1
kind: Secret
metadata:
  name: book-postgres-secret
type: Opaque
stringData:
  connection-string: "Host=book-postgres;Port=5432;Database=BookDB;Username=book_user;Password=book_password;Timeout=30;Command Timeout=30"
