apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:latest
          command: ['sh', '-c', 'until pg_isready -h review-postgres -p 5432 -U review_user; do echo waiting for postgres; sleep 2; done;']
        - name: wait-for-rabbitmq
          image: busybox
          command: [ 'sh', '-c', 'until nc -z review-rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;' ]
      containers:
        - name: review-service
          image: review-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: Keycloak__Authority
              value: "http://keycloak:8080/realms/BookReview"
            - name: Keycloak__ExternalAuthority
              value: "http://auth.review.local/realms/BookReview"
            - name: Keycloak__ClientId
              value: "review-service"
            - name: RabbitMQ__Host
              value: "review-rabbitmq"
            - name: RabbitMQ__Username
              value: "guest"
            - name: RabbitMQ__Password
              value: "guest"
            - name: MessageBus__ServiceSecretKey
              valueFrom:
                secretKeyRef:
                  name: review-service-secret
                  key: service-key
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: review-postgres-secret
                  key: connection-string
