apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-keycloak
  template:
    metadata:
      labels:
        app: review-keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: review-keycloak-data-pvc
